using hostname.

[code language="java"]
node {

    withMaven(maven:'maven') {

        stage('Checkout') {
        https://github.com/leo-coutinho
            git url: 'https://github.com/leo-coutinho/acu-menglobal-microservices.git', credentialsId: 'leo-coutinho', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('faces-service') {
                def app = docker.build "localhost:5000/faces-service:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("localhost:5000/faces-service:${env.version}").run('-p 2222:2222 -h account --name account --link discovery')
        }

        stage ('Final') {
            build job: 'customer-service-pipeline', wait: false
        }

    }

}
