info:
  component: Edge Server

server:
  port: ${PORT:8765}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    account:
      path: /faces/**
      serviceId: faces-services
#    customer:
#      path: /customer/**
#      serviceId: customer-service
#    product:
#      path: /product/**
#      serviceId: product-service
#    transfer:
#      path: /transfer/**
#      serviceId: transfer-service

hystrix:
   command:
      default:
         execution:
            timeout:
               enabled: false

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
